# Generated by Django 4.2.5 on 2023-09-11 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaguploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploads',
            name='imgname',
            field=models.ImageField(upload_to='img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
